Do not abort / exit in read_nr func.

diff --git a/belegnr b/belegnr
--- a/belegnr
+++ b/belegnr
@@ -33,8 +33,13 @@ EOF
 
 # Abort script with an error message.
 abort() {
-	echo "${SCRIPT_NAME}: $*" >&2
+	warn "$*"
 	exit 1
+}
+
+# Print warning on stderr.
+warn() {
+	echo "${SCRIPT_NAME}: $*" >&2
 }
 
 # Ask for confirmation.
@@ -76,11 +81,13 @@ create_nr() {
 
 # Read and validate current number from file.
 read_nr() {
-	if ! nr=$(cat "${BELEGNR_FILE}"); then
-		abort "could not read file: ${BELEGNR_FILE}"
+	if ! nr=$(cat "${BELEGNR_FILE}" 2> /dev/null); then
+		warn "could not read file: ${BELEGNR_FILE}"
+		return 1
 	fi
 	if ! [ "${nr}" -ge 0 ] 2> /dev/null; then
-		abort "file contains no valid number: ${BELEGNR_FILE}"
+		warn "file contains no valid number: ${BELEGNR_FILE}"
+		return 1
 	fi
 	echo "${nr}"
 }
@@ -114,7 +121,7 @@ while getopts 'chpr:' opt; do
 			exit 0
 			;;
 		p)
-			nr=$(read_nr)
+			nr=$(read_nr) || exit 1
 			print_nr "${nr}"
 			;;
 		r)
