Always use var. name "nr" to store number.

diff --git a/belegnr b/belegnr
--- a/belegnr
+++ b/belegnr
@@ -50,10 +50,10 @@ confirm() {
 
 # Reset counter.
 reset_counter() {
-	_start="$1"
+	nr="$1"
 	confirm "Really reset counter?" || return
-	write_nr "${_start}"
-	print_nr "${_start}"
+	write_nr "${nr}"
+	print_nr "${nr}"
 }
 
 # Create new document number.
@@ -72,22 +72,24 @@ new_nr() {
 
 # Read and validate current number from file.
 read_nr() {
-	_nr=$(cat "${BELEGNR_FILE}") || abort "could not read file: ${BELEGNR_FILE}"
-	[ "${_nr}" -ge 0 ] 2> /dev/null || abort "file contains no valid number: ${BELEGNR_FILE}"
-	echo "${_nr}"
+	nr=$(cat "${BELEGNR_FILE}") || abort "could not read file: ${BELEGNR_FILE}"
+	[ "${nr}" -ge 0 ] 2> /dev/null || abort "file contains no valid number: ${BELEGNR_FILE}"
+	echo "${nr}"
 }
 
 # Write current number to file.
 write_nr() {
+	nr="$1"
 	tmp=$(mktemp) || abort "failed to create temporary file"
-	if ! (echo "$1" > "${tmp}" && mv -f "${tmp}" "${BELEGNR_FILE}"); then
+	if ! (echo "${nr}" > "${tmp}" && mv -f "${tmp}" "${BELEGNR_FILE}"); then
 	       abort "could not write file: ${BELEGNR_FILE}"
 	fi
 }
 
 # Print the formatted document number.
 print_nr() {
-	echo "${PREFIX}$1"
+	nr="$1"
+	echo "${PREFIX}${nr}"
 }
 
 # Abort, if $HOME is not set.
