Fix shellcheck SC2025.

diff --git a/belegnr b/belegnr
--- a/belegnr
+++ b/belegnr
@@ -78,7 +78,9 @@ fi
 
 # Write current number atomically.
 tmp=$(mktemp) || abort "failed to create temporary file"
-echo "${nr}" > "${tmp}" && mv -f "${tmp}" "${file}" || abort "could not write file: ${file}"
+if ! (echo "${nr}" > "${tmp}" && mv -f "${tmp}" "${file}"); then
+       abort "could not write file: ${file}"
+fi
 
 # Output the formatted document number.
 echo "${prefix}${nr}"
